static: "static"

routes:
    - url: "/"
      handler: "About->index"
    - url: "/login"
      handler: "Login->login"
    - url: "/logout"
      handler: "Login->logout"
    - url: "/user{num}"
      handler: "User->view"
    - url: "/settings"
      handler: "User->settings"
    - url: "/create"
      handler: "Article->create"
    - url: "/a{num}"
      handler: "Article->view"
    - url: "/articles"
      handler: "Article->allArticles"
    - url: "/blob_{text}/{text}.{text}"
      handler: "Blob->file"